---
- name: "Check for haproxy_exporter binary"
  stat:
    path: '{{ haproxy_exporter_install_dir }}/haproxy_exporter'
  changed_when: false
  register: haproxy_exporter_install

- when: not haproxy_exporter_install.stat.exists or haproxy_exporter_force_install|bool
  block:
    - name: "Create haproxy_exporter system group"
      group:
        name: "{{ haproxy_exporter_group }}"
        system: true
        state: present

    - name: "Create haproxy_exporter system user"
      user:
        name: "{{ haproxy_exporter_group }}"
        system: true
        shell: "/usr/sbin/nologin"
        group: "{{ haproxy_exporter_group }}"
        append: true
        createhome: false
        home: /tmp

    - name: "Install requierements"
      package:
        name: "ca-certificates"
        state: present

    - name: "Download haproxy_exporter..."
      get_url:
        url: '{{ haproxy_exporter_tgz_url }}'
        dest: '{{ haproxy_exporter_temp_dir }}/{{ haproxy_exporter_tgz }}'
        timeout: '60'
        mode: '0644'

    - name: "Ensure install dir exists"
      file:
        path: '{{ item }}'
        state: directory
        mode: '0755'
      with_items:
        - '{{ haproxy_exporter_install_dir }}'
        - '{{ haproxy_exporter_temp_dir }}/haproxy_exporter'

    - name: "Unarchive haproxy_exporter..."
      unarchive:
        src: '{{ haproxy_exporter_temp_dir }}/{{ haproxy_exporter_tgz }}'
        dest: '{{ haproxy_exporter_temp_dir }}/haproxy_exporter'
        extra_opts: [--strip-components=1]
        remote_src: true
        mode: '0644'

    - name: "Copy haproxy_exporter binary..."
      copy:
        src: '{{ haproxy_exporter_temp_dir }}/haproxy_exporter/haproxy_exporter'
        dest: '{{ haproxy_exporter_install_dir }}/haproxy_exporter'
        remote_src: true
        mode: '0755'

    - name: "Remove temporary directory"
      file:
        path: '{{ haproxy_exporter_temp_dir }}/haproxy_exporter'
        state: absent

- name: "Create systemd for haproxy_exporter"
  template:
    src: 'haproxy_exporter.service.j2'
    dest: '/etc/systemd/system/haproxy_exporter.service'
    mode: '0644'
  notify: "restart haproxy_exporter"

- name: "Start haproxy_exporter.service"
  service:
    name: haproxy_exporter
    state: started
    enabled: true
    daemon_reload: true
